### ISSUE TITLE
Tracking issue for grids

### ISSUE THREAD

**Issue by mindriot101** [milliams/plotlib#28]
This issue tracks the features we want to add to showing grids.

## Checklist

- [x] Basic grid support (#23)
- [ ] configuring grid colour
- [ ] basing grid spacing on the plot range
- [ ] configuring what z-index the grid has
- [ ] overriding our defaults for horizontal vs both
- [ ] logarithmic grids
- [ ] support the text output
